# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/en/latest/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/en/latest/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/en/latest/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

language: python
python:
   - "2.7"

sudo: false
cache:
   directories:
       - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/_0010_Blink
    - PLATFORMIO_CI_SRC=examples/_0012_ADC
    - PLATFORMIO_CI_SRC=examples/_0020_BlinkESPert
    - PLATFORMIO_CI_SRC=examples/_0030_BoardInfo
    - PLATFORMIO_CI_SRC=examples/_0040_Button
    - PLATFORMIO_CI_SRC=examples/_0050_OLED
    - PLATFORMIO_CI_SRC=examples/_0060_DHT
    - PLATFORMIO_CI_SRC=examples/_0070_SmartConfig
    - PLATFORMIO_CI_SRC=examples/_0080_WebServer
    - PLATFORMIO_CI_SRC=examples/_0090_Ajax
    - PLATFORMIO_CI_SRC=examples/_0100_HttpGet
    - PLATFORMIO_CI_SRC=examples/_0110_ButtonToPushMessage
    - PLATFORMIO_CI_SRC=examples/_0130_MQTT_Button
    - PLATFORMIO_CI_SRC=examples/_0140_MQTT_DHT
    - PLATFORMIO_CI_SRC=examples/_0150_MQTT_LED
    - PLATFORMIO_CI_SRC=examples/_0160_Time_SNTP
    - PLATFORMIO_CI_SRC=examples/_1000_Buzzer
    - PLATFORMIO_CI_SRC=examples/_1010_MQTT_LED_Buzzer
    - PLATFORMIO_CI_SRC=examples/_1020_PIR
    - PLATFORMIO_CI_SRC=examples/_1030_ExternalButton
    - PLATFORMIO_CI_SRC=examples/_1040_Sleep
    - PLATFORMIO_CI_SRC=examples/_2000_ESPert_workshop
    - PLATFORMIO_CI_SRC=examples/_3001_NeoPixel
    - PLATFORMIO_CI_SRC=examples/_9000_Game_Octopus
install:
   - pip install -U platformio
   - platformio lib install 19 28 64 66 89 562


script:
   - python extras/extra_ci.py
   - find .
   - platformio ci --board=espresso_lite_v2 --lib="."
